# Generated by Django 3.2.7 on 2021-09-17 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assis_tech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
