# Generated by Django 3.2.7 on 2021-09-18 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assis_tech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cpf',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
