# Generated by Django 4.1.1 on 2022-09-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assis_tech', '0003_categoria_relato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cpf',
            field=models.CharField(max_length=30),
        ),
    ]
