# Generated by Django 4.1.1 on 2022-09-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assis_tech', '0005_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cpf',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
